### ISSUE TITLE
Typing in the "Speakers name" field causes the "+" to shift position in the UI

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#19]
- Be on speaker setup screen
- Toggle "Has Nostr profile" to OFF
- Type anything in the "Speaker's name" field

Result:
<img width="453" alt="Screenshot 2023-11-07 at 22 49 08" src="https://github.com/owen1917/event-zapper/assets/123519473/92ab8451-9807-433c-baac-d74c4cf0f550">

Expected - "+" would remain in original position:
<img width="448" alt="Screenshot 2023-11-07 at 22 52 17" src="https://github.com/owen1917/event-zapper/assets/123519473/08900a67-e71c-4f0b-8625-9d3adf075ef2">

**Comment by fjordskii** [comment]
https://github.com/owen1917/event-zapper/pull/4
