### ISSUE TITLE
Regression: Zaps no longer showing up for speakers with "Has nostr profile" toggled on

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#20]
- Setup multiple speakers as follows, configure them all with the name npub
   - 2 with "Has nostr profile" toggled on
   - 1 with "Has nostr profile" toggled off
 - Click present
 - Zap the profile of the specified npub
 - Issue: Zaps only appear under the speaker configured with "Has nostr profile" toggled off
 - Expected: All speakers are configured with the same npub, I should see the same zaps under all speakers

<img width="1433" alt="Screenshot 2023-11-07 at 22 54 50" src="https://github.com/owen1917/event-zapper/assets/123519473/6366a565-35c7-401d-a069-ad28d407cd16">

<img width="1440" alt="Screenshot 2023-11-07 at 22 54 31" src="https://github.com/owen1917/event-zapper/assets/123519473/2b67c7fc-9a49-44f1-a508-6dc66472df5f">

**Comment by fjordskii** [comment]
zaps are showing again, looks like the `npub` got doubled up https://github.com/owen1917/event-zapper/pull/4
