### ISSUE TITLE
Adding speakers before npub is populated causes name and profile picture not to be populated correctly in speaker or presentation view

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#21]
- Rapidly paste npubs and click "Add speaker"
- Notice that profile name and picture are **not populated**
- Click "Present"
- Notice that profile name and picture are **not populated** on this screen either

Expected: Prevent user from adding speaker until profile is pulled OR continue populating a-sync after the user clicks "add speaker"

https://github.com/owen1917/event-zapper/assets/123519473/93d9cb2f-02aa-49cd-92ed-2db2a26d7f94

**Comment by fjordskii** [comment]
https://github.com/owen1917/event-zapper/pull/4
