### ISSUE TITLE
Prevent layout issues if the user has a really long name

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#22]
Edge case. I'm not sure what the solution is for this (if any). Open to suggests on how the UI can react more gracefully to super long names

https://github.com/owen1917/event-zapper/assets/123519473/4e7ccc95-4c64-40ab-a778-12827c221995

**Comment by fjordskii** [comment]
Fixed this by removing the name preview as user types and then trimming long names after 25 characters i.e.:
<img width="466" alt="Screenshot 2023-11-13 at 8 05 31 PM" src="https://github.com/owen1917/event-zapper/assets/5777822/90b83b7c-9e62-470d-9539-fb3461f4bca2">
