### ISSUE TITLE
Should we revert "image embedded in QR code" changes?

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#23]
Not sure I like the look of these changes https://github.com/owen1917/event-zapper/issues/16 - what do you think @fjordskii ?

<img width="1434" alt="Screenshot 2023-11-07 at 23 30 06" src="https://github.com/owen1917/event-zapper/assets/123519473/2ecb0be0-06d1-4a07-a74d-ce3576ecbab5">

I think the profile image is super important to display as large as possible, and it doesn't seem like its feasible with it embedded within the QR code, without jepordzijng the usability of the QR.

In my opinion, we should revert to the previous layout.

Alternatively, the QR could be displayed next to the profile picture, to save space. Honestly, open to experimentation here!

<img width="1093" alt="Screenshot 2023-11-07 at 23 27 39" src="https://github.com/owen1917/event-zapper/assets/123519473/1cca6dd1-3b19-4a7d-be6e-f919abd50488">

**Comment by fjordskii** [comment]
Agreed - I reverted, still messing with the look but the image is removed from qr code now https://github.com/owen1917/event-zapper/pull/4
