### ISSUE TITLE
"⚡️X Sats Zapped" sometimes because untethered from the bottom right of the presentation screen

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#24]
<img width="1436" alt="Screenshot 2023-11-07 at 23 25 32" src="https://github.com/owen1917/event-zapper/assets/123519473/b1376614-bfb3-4897-8559-801564fc5b52">

Expected:  "⚡️X Sats Zapped"  will remain in the bottom right corner of the presentation screen

**Comment by fjordskii** [comment]
This should be fixed, im also in the middle of redesigning everything in presentation view so some other stuff might be broken in the mean time
