### ISSUE TITLE
Clear all fields if user toggles "Has nostr profile"

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#25]
- Go to speaker setup page
- Populate the npub field
- Toggle "Has nostr profile" OFF
- Observe how some of the information (image, name) is still populated
- Populate the "donation npub" field
- Toggle "Has nostr profile" ON
- Add the speaker
- Speaker is added but displayed with both npub and donation nub

Expected: If "Has nostr profile" is toggled, clear speaker field contents to prevent weird edge cases

https://github.com/owen1917/event-zapper/assets/123519473/729ca8c6-409a-432b-ba2e-d84487c7c7ca

**Comment by fjordskii** [comment]
https://github.com/owen1917/event-zapper/pull/4
