### ISSUE TITLE
UX feedback: "Please paste your npub above' could confuse users

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#27]
Noticed the addition of "Please paste your npub above"

I feel like this might confuse users in to paste their own npub, as opposed the the person speaking. I feel like this is already covered by the field title "Speaker's public key (npub)"

<img width="576" alt="Screenshot 2023-11-09 at 00 13 53" src="https://github.com/owen1917/event-zapper/assets/123519473/2008c060-79c0-4472-a590-20676c5d8571">

**Comment by fjordskii** [comment]
agreed, removed!
