### ISSUE TITLE
Improvement: Generated QR code should link to njump.me

### ISSUE THREAD

**Issue by owen1917** [owen1917/event-zapper#29]
Presently, Event Zapper generates a QR code based on the speaker's npub. When scanning the QR code in presentation view, it opens the link `nostr:[SPEAKERS NPUB]`. The expected behavior is for this link to open in the user's default native client.

During my testing, primarily on iOS/Damus, this functions as anticipated, and the link opens in the Damus client, directing the user to the speaker's profile.

Subsequent testing reveals that this does not perform equally well with all clients:

- Android/Amethyst (most popular Android client): Opens the app but fails to open the user profile.
- Android/Current app: Does not open the app at all.
- iOS/Primal app: Does not open the app at all.

It is evident that these clients need to address this issue. However, relying on them to do so is not a viable solution.

The proposed resolution here is to generate a QR code that opens a jump link instead.`https://njump.me/npub1am50jqjytzdtepftqfzf8grh2gs4wpt7d4t90zxc6z288wqazj5skdks29`

![Event Zapper - Solving the problem that few clients allow profile zaps copy](https://github.com/owen1917/event-zapper/assets/123519473/3bb528a6-525c-4026-abac-6ac99dab98ce)

.. from here, the audience member can decide how/with which client to view the speaker's nostr profile

**Comment by fjordskii** [comment]
@owen1917 pushed! check it out, QR code should go to `njump` now
